trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: mirror-azure-devops-to-github

steps:
- checkout: self
  fetchDepth: 0

- script: |
    git config --global user.email "patidarrambabu135@gmail.com"
    git config --global user.name "Azure DevOps Mirror"

    git remote add github https://$(GITHUB_USERNAME):$(GITHUB_TOKEN)@github.com/rambabu-patidar/iaac-cid-cd-learning.git

    git push --prune github "+refs/remotes/origin/*:refs/heads/*" "+refs/tags/*:refs/tags/*"
  displayName: 'Mirror Repository'